/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.View;

import br.edu.model.Utilitários;
import java.text.DecimalFormat;

/**
 *
 * @author PC
 */
public class CalculadoraView extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraView
     */
    public CalculadoraView() {
        initComponents();
        
         Utilitários u = new Utilitários();
        u.InserirIcone(this);
        
        jButton5.setContentAreaFilled(false);
        jButton6.setContentAreaFilled(false);
        jButton7.setContentAreaFilled(false);
        jTPeso.setBackground(new java.awt.Color(0,0,0,1));
        jTAltura.setBackground(new java.awt.Color(0,0,0,1));
        jTIdade.setBackground(new java.awt.Color(0,0,0,1));
    }
    
    double peso,altura,imc;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTPeso = new javax.swing.JTextField();
        jTIdade = new javax.swing.JTextField();
        jTAltura = new javax.swing.JTextField();
        jBCalcular = new javax.swing.JButton();
        jLResultado = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora IMC");
        getContentPane().setLayout(null);

        jTPeso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTPeso.setForeground(new java.awt.Color(102, 102, 102));
        jTPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTPeso.setBorder(null);
        getContentPane().add(jTPeso);
        jTPeso.setBounds(80, 170, 90, 40);

        jTIdade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTIdade.setForeground(new java.awt.Color(102, 102, 102));
        jTIdade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTIdade.setBorder(null);
        jTIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(jTIdade);
        jTIdade.setBounds(200, 170, 90, 40);

        jTAltura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTAltura.setForeground(new java.awt.Color(102, 102, 102));
        jTAltura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTAltura.setBorder(null);
        jTAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTAlturaActionPerformed(evt);
            }
        });
        getContentPane().add(jTAltura);
        jTAltura.setBounds(80, 240, 90, 30);

        jBCalcular.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBCalcular.setBorderPainted(false);
        jBCalcular.setContentAreaFilled(false);
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jBCalcular);
        jBCalcular.setBounds(200, 230, 80, 40);

        jLResultado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLResultado.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLResultado);
        jLResultado.setBounds(180, 280, 130, 30);

        jButton5.setBackground(new java.awt.Color(67, 62, 96));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("SAIR");
        jButton5.setBorder(null);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(190, 0, 80, 30);

        jButton6.setBackground(new java.awt.Color(67, 62, 96));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("VOLTAR");
        jButton6.setBorder(null);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(10, 0, 70, 30);

        jButton7.setBackground(new java.awt.Color(67, 62, 96));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("AJUDA");
        jButton7.setBorder(null);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(100, 0, 80, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/CalculadoraIMC.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 720, 490);

        setSize(new java.awt.Dimension(734, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
       peso = Double.parseDouble(jTPeso.getText());
       altura = Double.parseDouble(jTAltura.getText());
       imc = peso/(altura * altura);
        
        DecimalFormat formato = new DecimalFormat("00.0");
        String ABC = formato.format(imc);
        
       
        jLResultado.setText(String.valueOf(ABC));
        
       
    }//GEN-LAST:event_jBCalcularActionPerformed

    private void jTIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIdadeActionPerformed

    private void jTAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTAlturaActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        this.dispose();

    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        this.dispose();
        new LoginView().setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
        new SelectView().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       new TelaDeAjuda1View().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCalcular;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLResultado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTAltura;
    private javax.swing.JTextField jTIdade;
    private javax.swing.JTextField jTPeso;
    // End of variables declaration//GEN-END:variables
}
